name: defioptimized_yield
description: "A new Flutter project."
 
 
publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


   
   
  cupertino_icons: ^1.0.6
  get:
  google_fonts:
  smooth_page_indicator:
  flutter_svg:
  otp_text_field:
  iconsax:
  animated_bottom_navigation_bar:
  gap:
  auto_size_text:
  buttons_tabbar:
  syncfusion_flutter_datepicker:
  dotted_border:
  equatable:
  file_picker:
  permission_handler:
  mime:
  intl:
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  build_runner:
  build_web_compilers:

 
flutter:

  uses-material-design: true


  assets:
    - asset/image/
    - asset/image/GIF/
    - asset/SVG/Logo/
    - asset/SVG/Icon/
   
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
